### ISSUE TITLE
Autoloading

### ISSUE THREAD

**Issue by adhamu** [reevoo/reevoomark-php-api#7]
This API doesn't look like it can be autoloaded. 

Can you create an autoload declaration in the `composer.json` file (e.g. PSR-0)?

**Comment by chrisemerson** [comment]
+1. One of the main reasons/benefits of composer is that each package defines it's own auto-loading strategy, so that clients only have to include the composer generated autoloader and all packages just work, whatever strategy they are using.

Requiring clients to individually 'require' your libraries files when they need them works against this aim, and just makes the library harder to use - there's not much point in using composer just to act as a download manager, seems a bit half-baked!

**Comment by errm** [comment]
#8 fixed this
